// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using c05_SpaSmart.Data;

#nullable disable

namespace c05_SpaSmart.Migrations
{
    [DbContext(typeof(SpaSmartDbContext))]
    partial class SpaSmartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("c05_SpaSmart.Models.ChiTietLichHen", b =>
                {
                    b.Property<int>("LichHenId")
                        .HasColumnType("int");

                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTienLucDat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LichHenId", "DichVuId");

                    b.HasIndex("DichVuId");

                    b.ToTable("ChiTietLichHens");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.DanhMucPhuLieu", b =>
                {
                    b.Property<int>("DichVuId")
                        .HasColumnType("int");

                    b.Property<int>("PhuLieuId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTieuHao")
                        .HasColumnType("int");

                    b.HasKey("DichVuId", "PhuLieuId");

                    b.HasIndex("PhuLieuId");

                    b.ToTable("DanhMucPhuLieus");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.GoiDichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GoiDichVus");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.KyThuatVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThaiKTV")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KyThuatViens");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.LichHen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KyThuatVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGioDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayLapHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienGiamGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KyThuatVienId");

                    b.HasIndex("UserId");

                    b.ToTable("LichHens");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.PhieuChi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnhChungTu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDoChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PhieuChis");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.PhuLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HangSanXuat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenPhuLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TonKho")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhuLieus");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.ChiTietLichHen", b =>
                {
                    b.HasOne("c05_SpaSmart.Models.GoiDichVu", "GoiDichVu")
                        .WithMany("ChiTietLichHens")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("c05_SpaSmart.Models.LichHen", "LichHen")
                        .WithMany("ChiTietLichHens")
                        .HasForeignKey("LichHenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoiDichVu");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.DanhMucPhuLieu", b =>
                {
                    b.HasOne("c05_SpaSmart.Models.GoiDichVu", "GoiDichVu")
                        .WithMany("DanhMucPhuLieus")
                        .HasForeignKey("DichVuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("c05_SpaSmart.Models.PhuLieu", "PhuLieu")
                        .WithMany("DanhMucPhuLieus")
                        .HasForeignKey("PhuLieuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoiDichVu");

                    b.Navigation("PhuLieu");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.LichHen", b =>
                {
                    b.HasOne("c05_SpaSmart.Models.KyThuatVien", "KyThuatVien")
                        .WithMany("LichHens")
                        .HasForeignKey("KyThuatVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("c05_SpaSmart.Models.User", "User")
                        .WithMany("LichHens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KyThuatVien");

                    b.Navigation("User");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.PhieuChi", b =>
                {
                    b.HasOne("c05_SpaSmart.Models.User", "User")
                        .WithMany("PhieuChis")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.GoiDichVu", b =>
                {
                    b.Navigation("ChiTietLichHens");

                    b.Navigation("DanhMucPhuLieus");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.KyThuatVien", b =>
                {
                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.LichHen", b =>
                {
                    b.Navigation("ChiTietLichHens");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.PhuLieu", b =>
                {
                    b.Navigation("DanhMucPhuLieus");
                });

            modelBuilder.Entity("c05_SpaSmart.Models.User", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("PhieuChis");
                });
#pragma warning restore 612, 618
        }
    }
}
